services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token $TUNNEL_TOKEN
    networks:
      - tunnel #a name for the Cloudflare Network
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN:

  nginx:
    container_name: nginxmp
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '81:81' # Admin Web Port
      # - '5000:80' # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - tunnel #a name for the Cloudflare Network

networks:
  tunnel: #a name for the Cloudflare Network
